server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: logistics_tracking
    redis:
      host: localhost
      port: 6379
      database: 0


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  mail:
    host: smtp.example.com
    port: 587
    username: # 你自己所使用的邮箱
    password: # 你自己的邮箱key
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 高德地图配置
amap:
  key: # 你自己的高德地图key，每个api提供商调用api的方式不同，如果你使用的是其他api，那么这个项目可能无法正常运行
  geocodeUrl: https://restapi.amap.com/v3/geocode/geo
  regeoUrl: https://restapi.amap.com/v3/geocode/regeo
  distanceUrl: https://restapi.amap.com/v3/distance
  drivingUrl: https://restapi.amap.com/v3/direction/driving
  routeUrl: https://restapi.amap.com/v3/direction/driving
  directionUrl: https://restapi.amap.com/v3/direction/driving

# 日志配置
logging:
  level:
    com.logistics.tracking: DEBUG 
    org.springframework.web: INFO 